site_name: 電気からはじめるコンピュータ
nav:
  - Home: index.md
  - 第1章 物理学: 1_physics.md
  - 第2章 トランジスタ: 2_transistor.md
  - 第3章 論理回路: 3_logic.md
  - 1~3章補足: appendix_1_3.md
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
